// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7aWXL4vtJXGVh6DtKHs4uvmdsdP3-ElY',
    appId: '1:899508060219:web:fc397201e052474beb1c1e',
    messagingSenderId: '899508060219',
    projectId: 'dqol-new',
    authDomain: 'dqol-new.firebaseapp.com',
    storageBucket: 'dqol-new.appspot.com',
    measurementId: 'G-CK3HLRHH8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrepNXxzAvAjY0DQm20uWa-rir_XoN_mc',
    appId: '1:899508060219:android:b507b280e28f8924eb1c1e',
    messagingSenderId: '899508060219',
    projectId: 'dqol-new',
    storageBucket: 'dqol-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnfnisCo2iWlNtkaSSnrJsRmyTbnOPsGk',
    appId: '1:899508060219:ios:14932340b22cb937eb1c1e',
    messagingSenderId: '899508060219',
    projectId: 'dqol-new',
    storageBucket: 'dqol-new.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnfnisCo2iWlNtkaSSnrJsRmyTbnOPsGk',
    appId: '1:899508060219:ios:1b1cad988234521deb1c1e',
    messagingSenderId: '899508060219',
    projectId: 'dqol-new',
    storageBucket: 'dqol-new.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
